### ISSUE TITLE
Resource not found error when clicking on Tools -> Source Sync

### ISSUE THREAD

**Issue by stmlange** [fioan89/sourcesync#56]
```
Calling `ClassLoader#getResource` with leading slash doesn't work; strip

com.intellij.diagnostic.PluginException: /sourcesync.png [Plugin: org.wavescale.sourcesync]
	at com.intellij.ide.plugins.cl.PluginClassLoader.doFindResource(PluginClassLoader.java:492)
	at com.intellij.ide.plugins.cl.PluginClassLoader.findResource(PluginClassLoader.java:439)
	at java.base/java.lang.ClassLoader.getResource(ClassLoader.java:1401)
	at org.wavescale.sourcesync.ui.SourceSyncConfig$1.run(SourceSyncConfig.java:53)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:885)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:754)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:440)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

Using:
```
IntelliJ IDEA 2021.2.4 (Community Edition)
Build #IC-212.5712.43, built on December 21, 2021
Runtime version: 11.0.13+8-b1504.49 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1998M
Cores: 8
Registry: scala.erase.compiler.process.jdk.once=false
Non-Bundled Plugins: org.wavescale.sourcesync (1.9), com.github.novotnyr.gitlab-quickmr-idea-plugin (21), PMDPlugin (1.8.21), com.github.kornilovaL.flamegraphProfiler (1.0), com.intellij.ideolog (203.0.27.0), org.sonarlint.idea (6.3.1.40498), org.jetbrains.plugins.spotbugs (1.2.5), nl.rubensten.texifyidea (0.7.13), org.jetbrains.kotlin (212-1.6.10-release-923-IJ5457.46), org.intellij.scala (2021.2.29)
Kotlin: 212-1.6.10-release-923-IJ5457.46
```

**Comment by beyourwild7** [comment]
IntelliJ IDEA versions greater than 2021.1.3 does not support `Calling `ClassLoader#getResource` with leading slash`. Will be working on a patch for this.

**Comment by fioan89** [comment]
Hi all. I've just uploaded version 2.0.0 for sourcesync. The resource loading issue should be solved. It will take around 2 business day for Jetbrains to moderate and approve the plugin, so stay tuned.
