### ISSUE TITLE
java.lang.NoClassDefFoundError: com/jgoodies/forms/layout/FormLayout

### ISSUE THREAD

**Issue by ns-rkonka** [fioan89/sourcesync#59]
```
java.lang.NoClassDefFoundError: com/jgoodies/forms/layout/FormLayout
	at org.wavescale.sourcesync.ui.SourceSyncConfig.$$$setupUI$$$(SourceSyncConfig.java)
	at org.wavescale.sourcesync.ui.SourceSyncConfig.<init>(SourceSyncConfig.java:48)
	at org.wavescale.sourcesync.action.ActionSourceSyncMenu.actionPerformed(ActionSourceSyncMenu.java:21)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:244)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:265)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:244)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:300)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:236)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:67)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:292)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$3(ActionMenuItem.java:131)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:131)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:401)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
	at java.desktop/com.apple.laf.ScreenMenuItemCheckbox.itemStateChanged(ScreenMenuItemCheckbox.java:204)
	at java.desktop/java.awt.CheckboxMenuItem.processItemEvent(CheckboxMenuItem.java:396)
	at java.desktop/java.awt.CheckboxMenuItem.processEvent(CheckboxMenuItem.java:364)
	at java.desktop/java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:375)
	at java.desktop/java.awt.MenuComponent.dispatchEvent(MenuComponent.java:363)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:498)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: com.jgoodies.forms.layout.FormLayout PluginClassLoader(plugin=PluginDescriptor(name=Source Synchronizer, id=org.wavescale.sourcesync, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/PyCharmCE2021.3/plugins/sourcesync, version=1.9, package=null, isBundled=false), packagePrefix=null, instanceId=59, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:235)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 47 more
```

Pycharm CE: PyCharm 2021.3
Mac OS:  12.3

**Comment by fioan89** [comment]
Hi, it sounds like something is wrong with PyCharm's classpath. jgoodies library is provided by IDEA. Can you check in the install folder of PyCharm if there is any jgoodies-common jar file?

**Comment by ns-rkonka** [comment]
@fioan89 
I am not finding the lib. Did I search for it in right place?
```
ls /Users/xxxx/Library/Application Support/JetBrains/PyCharmCE2021.3
bundled_plugins.txt     inspection              plugins                 pycharm.vmoptions       tools
codestyles              options                 port                    ssl                     updatedBrokenPlugins.db
disabled_plugins.txt    plugin_PCWMP.license    port.lock               tasks                   workspace
```

**Comment by fioan89** [comment]
No, I think that is where PyCharm saves configuration, metadata, user installed plugins, etc..

You can search in /Applications folder
<img width="750" alt="image" src="https://user-images.githubusercontent.com/1479167/162189581-b742b613-ab6f-4c6d-88da-7dfbc2faf403.png">

**Comment by ns-rkonka** [comment]
@fioan89 
```
ls /Applications/PyCharm CE.app/Contents/plugins
IntelliLang                             github                                  pycharm-community-sharedIndexes-bundled svn4idea
completionMlRanking                     grazie                                  python-ce                               tasks
configurationScript                     hg4idea                                 python-sharedIndexes-downloadable       terminal
copyright                               indexing-shared                         pythonIDE                               textmate
cwm-plugin                              laf-macos                               rest                                    toml
cwm-plugin-projector                    markdown                                searchEverywhereMl                      vcs-changeReminder
editorconfig                            marketplace                             settings-repository                     vcs-git-featuresTrainer
featuresTrainer                         platform-images                         sh                                      yaml
git4idea                                properties                              space
```
Looks like I don't have java folder itself

**Comment by fioan89** [comment]
Not sure what happened IntelliJ seems to provide the library. As a quick solution  you could try to download the jar from https://mvnrepository.com/artifact/com.jgoodies/jgoodies-common/1.4.0 and put it in one of the plugin folders. In the meantime I will try to change the code  an get rid of jgoodies dependencies.

**Comment by ns-rkonka** [comment]
Thank you @fioan89

**Comment by fioan89** [comment]
Hi all. I've just uploaded version 2.0.0 for sourcesync. It gets rid of all dependencies on jgoodies and form layout. It will take around 2 business day for Jetbrains to moderate and approve the plugin, so stay tuned.
